[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    lvgl/lvgl@^9.4.0
    https://github.com/PaulStoffregen/XPT2046_Touchscreen

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include
    -D USER_SETUP_LOADED=1
    -include include/Setup_ESP32_2432S028R_ILI9341.h
    -D LV_CONF_INCLUDE_SIMPLE=1
    -D LV_USE_LOG=1
    -D LV_USE_TFT_ESPI=1