#pragma once
// config.h — system-wide tunables.

#define ENABLE_CLOUD_SYNC     true

#define SENSOR_READ_INTERVAL_MS      1000
#define STORAGE_WRITE_INTERVAL_MS    5000
#define CLOUD_SYNC_INTERVAL_MS       60000
#define HEALTH_CHECK_INTERVAL_MS     2000
#define DISPLAY_REFRESH_INTERVAL_MS  500

#define PRIORITY_SENSOR_TASK    3
#define PRIORITY_HEALTH_TASK    3
#define PRIORITY_STORAGE_TASK   2
#define PRIORITY_NETWORK_TASK   1
#define PRIORITY_DISPLAY_TASK   1

#define STACK_SENSOR_TASK    4096
#define STACK_STORAGE_TASK   4096
#define STACK_NETWORK_TASK   8192
#define STACK_DISPLAY_TASK   4096
#define STACK_HEALTH_TASK    4096

#define CORE_NETWORK_DISPLAY  0
#define CORE_SENSOR_HEALTH    1
